### ISSUE TITLE
Request for Rider to be added to PPA

### ISSUE THREAD

**Issue by Charl88** [JonasGroeger/jetbrains-ppa#1]
Hi there and thank you for the PPA.

Would you be able to add Rider? It would help cover all the languages Jetbrains offers solutions for.

**Comment by JonasGroeger** [comment]
I'm adding this right now.

**Comment by JonasGroeger** [comment]
You can install it now using

    sudo apt-add repository ppa:jonas-groeger/jetbrains-ppa
    sudo apt-get update
    sudo apt-get rider

**Comment by Charl88** [comment]
Thank you very much!
