### ISSUE TITLE
Add JetBrains Toolbox

### ISSUE THREAD

**Issue by MartinX3** [JonasGroeger/jetbrains-ppa#10]
https://www.jetbrains.com/toolbox/app/

**Comment by JonasGroeger** [comment]
I personally dont use the toolbox so feel free to make a PR.

**Comment by MartinX3** [comment]
Could you please reopen the issue, so I can close it with my Pull Request? :)

**Comment by MartinX3** [comment]
Hmm, there is a fault in the scripts in combination with the jetbrains tool box.
The entire version of it is a combination of version and "buildnumber".
So 1.6.2914 gets cut to 1.6, that's not good for updating packages, when only the minor version number changes.

I will investigate a solution.

**Comment by Vantuz** [comment]
Does this repo really need JB Toolbox? This is a tool to install/update JB software, actually a task this ppa solves. Also, I guess JB Toolbox won't work properly in `/opt/` directory without root permissions

**Comment by MartinX3** [comment]
It is fine to easily add software which isn't included in this ppa, but in the toolbox.
It also allows to update Software, which didn't get updated at this moment.

It also works fine in /opt/, because it installs the Software in the home folder, when started *without* sudo.

And it is also a jetbrains Software, and this ppa is for jetbrain products.
And some people prefer the toolbox instead of the Installation from each Software via apt install

So, it is fine to add it.

Am 12. Februar 2018 15:06:56 MEZ schrieb Vantuz <notifications@github.com>:
>Does this repo really need JB Toolbox? This is a tool to install/update
>JB software, actually a task this ppa solves. Also, I guess JB Toolbox
>won't work properly in `/opt/` directory without root permissions
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JonasGroeger/jetbrains-ppa/issues/10#issuecomment-364932057

-- 
Mit freundlichen Grüßen

Martin Dünkelmann

**Comment by Vantuz** [comment]
Imho it is easier to install toolbox as .tat.gz from JB site. I think use of toolbox eliminates the need to use this ppa. Also, toolbox won't be able to update itself if it's installed in /opt/

**Comment by MartinX3** [comment]
It is easier to apt install this peace of.
And also intellij can't update itself in /opt/
Every JetBrains Product has a self update mechanic.

And prefer to give the users of this ppa the freedom to choose if they prefer the toolbox vor the Software directly by this ppa

Am 12. Februar 2018 15:48:00 MEZ schrieb Vantuz <notifications@github.com>:
>Imho it is easier to install toolbox as .tat.gz from JB site. I think
>use of toolbox eliminates the need to use this ppa. Also, toolbox won't
>be able to update itself if it's installed in /opt/
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JonasGroeger/jetbrains-ppa/issues/10#issuecomment-364943897

-- 
Mit freundlichen Grüßen

Martin Dünkelmann
