### ISSUE TITLE
clion 2018

### ISSUE THREAD

**Issue by M1NDWARE** [JonasGroeger/jetbrains-ppa#17]
can u pls add clion 2018 ?

**Comment by Vantuz** [comment]
You can use [my ppa](https://launchpad.net/~vantuz/+archive/ubuntu/jetbrains)

**Comment by dylanmtaylor** [comment]
Can we get all the 2018.1 versions added?

**Comment by Vantuz** [comment]
I updated all packages in my ppa to current versions

**Comment by dylanmtaylor** [comment]
Cool, and I see you've made a pull request too. Thanks

**Comment by JonasGroeger** [comment]
Updated.
