### ISSUE TITLE
Clion upgrade and others

### ISSUE THREAD

**Issue by osiixy** [JonasGroeger/jetbrains-ppa#25]
Hi,
I am really grateful for your effort to maintain this PPA (I prefer repositories in every way).
There are newer version of the JetBrains products, such as Clion.

If you have some free time it would be wonderful to have them in your PPA.

(A humble Xenial user)

**Comment by JonasGroeger** [comment]
Hello @osiixy,

the current version of CLion is 2018.2.5 which is available in the repository for Xenial. I'm pretty sure thats an error on your end. Can you post the output of `apt-get update && apt-get upgrade` as well as `dpkg -l | grep clion` and `dpkg -L clion`

**Comment by osiixy** [comment]
Sorry  to have bothered you, but I had been using your LaunchPad PPA.
My bad, I haven't applied the RTFM rule, you are on Amazon now.
Thank you!

**Comment by JonasGroeger** [comment]
No worries :)
