### ISSUE TITLE
Support Ubuntu 20.04

### ISSUE THREAD

**Issue by raelgc** [JonasGroeger/jetbrains-ppa#32]
Ubuntu 20.04 (Focal Fossa) was released yesterday.

Please, add support for it

**Comment by AndreaGiardini** [comment]
Did you encounter any problem? It's working just fine for me

**Comment by raelgc** [comment]
@AndreaGiardini If you follow the instructions, but using `focal` (20.04 codename) instead of `bionic` (18.04 codename), the `apt update` will fail with errors. This is how most people using 20.04 will try to install.

I can see that if I keep the `bionic`, it'll work. Not usual (because often dependencies can be broken when you're cross installing `apt` repositories), but works.

**Comment by louiscklaw** [comment]
Can some command like this helps ?

**Origional:**
`echo "deb http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic main"`

**Modified:**
`echo "deb http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com $(lsb_release -cs) main"`

`lsb_release -cs` will output the host ubuntu's codename (e.g. focal for 20.04) to fit command running on different ubuntu versions

**Comment by raelgc** [comment]
@louiscklaw This was what I've tried, but the packages are published only for `bionic`. This is the reason why I've opened this issue.

**Comment by jdeluyck** [comment]
As @JonasGroeger is not reacting, I've replicated the travis ci setup, and i'm building the packages and serving them. Once Jonas comes back I'm more than willing to hand this back to him. 

https://github.com/jdeluyck/jetbrains-ppa
https://ppa-jetbrains.kcore.org/file/ppa-jetbrains/index.html

**Comment by JonasGroeger** [comment]
Fixed with #36
