### ISSUE TITLE
Fix the duplicated icons and .desktop files

### ISSUE THREAD

**Issue by lanzorg** [JonasGroeger/jetbrains-ppa#35]
There are two .desktop files when installing a jetbrains software.  
It's very strange and it's obviously a bug that needs to be fixed.

![](https://i.imgur.com/oYsyRRG.png)

![](https://i.imgur.com/v41ToAR.png)

![](https://i.imgur.com/UokWmmc.png)

I hope that you will soon find a solution. ;)

**Comment by JonasGroeger** [comment]
The `.desktop` files I'm installing is located in `/usr/share/applications/`. The other files are either from IntelliJ itself or from other installations.
