### ISSUE TITLE
apt-key is deprecated

### ISSUE THREAD

**Issue by gregorydk** [JonasGroeger/jetbrains-ppa#44]
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

apt-key will be last available in Debian 11 and Ubuntu 22.04. So maybe it's time to switch to `trusted.gpg.d`?

**Comment by JonasGroeger** [comment]
Thanks for reporting. I fixed it using the instructions at https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html
