### ISSUE TITLE
2022 versions not available through PPA

### ISSUE THREAD

**Issue by SkoZombie** [JonasGroeger/jetbrains-ppa#53]
When looking at available APT packages, 2022 versions are not available. The latest for pycharm-professional (for example) is 2021.3.2

Thanks again for this service, I just wanted to let you know in case Jetbrains broke something in your process.

**Comment by JonasGroeger** [comment]
Cannot reproduce:

```shell-session
$ apt show pycharm-professional
Package: pycharm-professional
Version: 2022.1
...

$ apt policy pycharm-professional
pycharm-professional:
  Installed: (none)
  Candidate: 2022.1
  Version table:
     2022.1 500
        500 http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any/main amd64 Packages
        500 http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any/main i386 Packages
...
```

Can you post your output here?

**Comment by SkoZombie** [comment]
Here's the output I get:

```
$ apt show pycharm-professional
Package: pycharm-professional
Version: 2021.3.2
Priority: extra
Section: devel
Maintainer: Jonas Gröger <jonas@huntun.de>
Installed-Size: 161 kB
Pre-Depends: wget
Homepage: https://www.jetbrains.com/
License: Proprietary
Vendor: https://www.jetbrains.com/
Download-Size: 144 kB
APT-Manual-Installed: yes
APT-Sources: http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic/main amd64 Packages
Description: Full-featured IDE for Python & Web development

N: There are 56 additional records. Please use the '-a' switch to see them.
$ apt policy pycharm-professional 
pycharm-professional:
  Installed: 2021.3.2
  Candidate: 2021.3.2
  Version table:
 *** 2021.3.2 500
        500 http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic/main amd64 Packages
        500 http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic/main i386 Packages
        100 /var/lib/dpkg/status
     2021.3.1 500
       .... (removed)
```

I got the same output on 2 different Linux Mint dev machines

I tried on a debian server that has never had it installed and got the same output as you so figured it must be something to do with the way my apt was configured. I dug into it and it seems that 'bionic' in the sources has changed to 'any'. I've been using your PPAs for quite a while, so my guess is this changed somewhere along the way?

Once I changed that in /etc/apt/sources.list.d/jetbrains-ppa.list I was able to get the 2022 versions.

Thanks for your help, hopefully this issue record will help someone else!

**Comment by JonasGroeger** [comment]
I added a hint to the README file just in case.

**Comment by AndreaGiardini** [comment]
I faced this issue as well! 

Ii noticed my pycharm version was outdated and I did not see any update in a while. I found this issue and replacing `bionic` with `any` fixed the problem.
