### ISSUE TITLE
ADD RustRover

### ISSUE THREAD

**Issue by allanlaal** [JonasGroeger/jetbrains-ppa#68]
https://www.jetbrains.com/rust/

**Comment by allanlaal** [comment]
waiting for https://data.services.jetbrains.com/products/releases?code=RR to start working (this gives us the download link)

**Comment by SkoZombie** [comment]
@allanlaal Just so you're aware, rustrover-eap is now available in this PPA, but from what I can see in data feed there's no official releases still. I worked with @JonasGroeger to add this support as I too was keen to play with rust

**Comment by lithedress** [comment]
Rustrover has been [released](https://blog.jetbrains.com/rust/2024/05/21/rustrover-is-released-and-includes-a-free-non-commercial-option/). The current build version is [241.17011.169](https://www.jetbrains.com/rust/download/#section=linux).
However, Rustrover in PPA is still EAP now.

**Comment by SkoZombie** [comment]
RustRover is in the PPA. I've installed 2024.3 and verified that it works properly.

@JonasGroeger you can probably close this issue
