### ISSUE TITLE
Automatic Build on CI

### ISSUE THREAD

**Issue by MartinX3** [JonasGroeger/jetbrains-ppa#7]
Please add a second contributor, which could add newer versions of the products and start the launchpad build process.

**Comment by JonasGroeger** [comment]
Ideally I was thinking a Jenkins / Travis build for this but I haven't found out how to reliably copy packages on launchpad from i.e. `artful` to other releases without an interactive session, since the launchpad api is kind of weird.

**Comment by MartinX3** [comment]
So you need to activate the build process by hand after every update?

**Comment by JonasGroeger** [comment]
Yes as of right now. However I think the process is ripe for automation. Don't have the time to implement it though

**Comment by MartinX3** [comment]
Can I help you?
Do I need to make the changes in this repo or do I need to have access to Launchpad?

**Comment by JonasGroeger** [comment]
Ideally you would test it with your own launchpad account and create your own PPA for testing purposes.
Then you would write code to make an automatic deployment when a new version from jetbrains gets released. The hard part is uploading the source packages to launchpad and waiting for the binary packages to be built to copy them from the newest release `artful` to all other currently supported releases. Thats the hard part.
Once it works you can create a PR.

**Comment by Vantuz** [comment]
It is possible to upload separate source package for all releases. That way no need to wait for binaries to be built

**Comment by MartinX3** [comment]
Yes, that's right.
Because sometimes, the packages need special adjustments for every distro, like dofferent dependencies.

Am 9. Februar 2018 12:36:39 MEZ schrieb Vantuz <notifications@github.com>:
>It is possible to upload separate source package for all releases. That
>way no need to wait for binaries to be built
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JonasGroeger/jetbrains-ppa/issues/7#issuecomment-364410824

-- 
Mit freundlichen Grüßen

Martin Dünkelmann

**Comment by MartinX3** [comment]
An example launchpad.cfg would make that easier for me.

**Comment by JonasGroeger** [comment]
You can create one using `launchpad_create_credentials`. Should be four lines.

**Comment by MartinX3** [comment]
Ahh
in terminal
`pip install launchpadlib`
`python launchpad_create_credentials jetbrains` jetbrains = my ppa name

**Comment by Vantuz** [comment]
Yea, guess we need some proper documentation

**Comment by MartinX3** [comment]
I'm working on a Dokumentation and a script, which ask for the right informations and generate the right files

Am 12. Februar 2018 15:02:18 MEZ schrieb Vantuz <notifications@github.com>:
>Yea, guess we need some proper documentation
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JonasGroeger/jetbrains-ppa/issues/7#issuecomment-364930877

-- 
Mit freundlichen Grüßen

Martin Dünkelmann

**Comment by dylanmtaylor** [comment]
I might play around with this and TravisCI a little bit. I might be able to get it working

**Comment by JonasGroeger** [comment]
I'm looking into setting up CI with `fpm` and `aptly` as well as `Amazon S3`. Stay tuned!

**Comment by JonasGroeger** [comment]
Under https://travis-ci.org/JonasGroeger/jetbrains-ppa you can now see that this project has been automated regarding updates. However, the publishing step is still tbd.

**Comment by JonasGroeger** [comment]
First version live @ https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/index.html

**Comment by JonasGroeger** [comment]
Still have to setup automatic publishing to there with travisci

**Comment by JonasGroeger** [comment]
Automatic publishing works now with https://travis-ci.org/JonasGroeger/jetbrains-ppa/jobs/372739014/config

**Comment by JonasGroeger** [comment]
So I guess this can be closed :)
