### ISSUE TITLE
Switch to native launcher for IDEs

### ISSUE THREAD

**Issue by uranderu** [JonasGroeger/jetbrains-ppa#72]
Hi,

First of all, thank you for providing this PPA!
When starting up the latest version of IDEA Ultimate I got a notification that I should switch to the native launcher. It is described in a YouTrack issue here ([link](https://youtrack.jetbrains.com/articles/SUPPORT-A-56/Switch-to-a-native-launcher-notification)).
I am not familiar with this kind of software development, but it might be as simple as removing the ".sh" for your launch scripts in /usr/bin for the different IDEs.

**Comment by Spurlos** [comment]
This is the difference between the shortcut created by PPA installer and the one that is created by IDE itself.

```
cd /usr/share/applications/
ls -la | grep php

-rw-r--r--   1 root root   260 Aug 13 17:11 jetbrains-phpstorm.desktop
-rw-r--r--   1 root root   187 Aug 22 13:13 phpstorm.desktop

cat phpstorm.desktop

[Desktop Entry]
Name=PhpStorm
Comment=Lightning-smart PHP IDE.
Exec=phpstorm %u
Icon=phpstorm
Terminal=false
Type=Application
Categories=Development;IDE;
StartupWMClass=jetbrains-phpstorm

cat jetbrains-phpstorm.desktop

[Desktop Entry]
Version=1.0
Type=Application
Name=PhpStorm
Icon=/opt/phpstorm/bin/phpstorm.svg
Exec="/opt/phpstorm/bin/phpstorm" %f
Comment=Lightning-smart PHP IDE
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-phpstorm
StartupNotify=true

which phpstorm

/usr/bin/phpstorm

cat /usr/bin/phpstorm

#!/bin/sh
exec "/opt/phpstorm/bin/phpstorm.sh" "$@"
```
